/**
 * AudienceIQ — Export Utilities
 */

export function exportMarkdown(result, description, docType, domain) {
  const lines = [
    `# Audience Brief: ${result.personaName}`,
    ``,
    `**Generated:** ${new Date().toLocaleDateString('en-GB', { day:'2-digit', month:'short', year:'numeric' })}`,
    `**Doc type:** ${docType || 'Unspecified'}`,
    `**Domain:** ${domain || 'Unspecified'}`,
    ``,
    `## Audience Description`,
    ``,
    description,
    ``,
    `## Knowledge Profile`,
    ``,
    ...result.bars.map(b => `- **${b.label}:** ${(b.value / 10).toFixed(1)}/10`),
    ``,
    `## Recommended Vocabulary`,
    ``,
    result.vocabRecommended.map(v => `- ${v}`).join('\n'),
    ``,
    `## Vocabulary to Avoid`,
    ``,
    result.vocabAvoid.map(v => `- ${v}`).join('\n'),
    ``,
    `## Knowledge Gaps`,
    ``,
    ...result.gaps.map(g => `### [${g.severity.toUpperCase()}] ${g.gap}\n${g.action}\n`),
    `## Tone Guidance`,
    ``,
    `**Use:**`,
    result.toneUse.map(t => `- ${t}`).join('\n'),
    ``,
    `**Avoid:**`,
    result.toneAvoid.map(t => `- ${t}`).join('\n'),
    ``,
    `## Reader Journey`,
    ``,
    ...result.journey.map((j, i) => `${i + 1}. **${j.title}** — ${j.desc}`),
    ``,
    `## Brief`,
    ``,
    result.briefText,
    ``,
    `---`,
    ``,
    `### Target Metrics`,
    ``,
    ...result.briefStats.map(s => `- **${s.label}:** ${s.value}`),
    ``,
    `---`,
    `*Generated by AudienceIQ — audienceiq.ai-engineer.app*`,
  ]

  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' })
  downloadBlob(blob, `audience-brief-${slug(result.personaName)}.md`)
}

export function exportText(result) {
  const lines = [
    `AUDIENCE BRIEF: ${result.personaName.toUpperCase()}`,
    `Generated: ${new Date().toLocaleDateString('en-GB', { day:'2-digit', month:'short', year:'numeric' })}`,
    ``,
    result.briefText,
    ``,
    `TARGET METRICS`,
    result.briefStats.map(s => `${s.label}: ${s.value}`).join('  |  '),
    ``,
    `--- Generated by AudienceIQ ---`,
  ]
  const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
  downloadBlob(blob, `audience-brief-${slug(result.personaName)}.txt`)
}

export async function copyToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    // Fallback
    const ta = document.createElement('textarea')
    ta.value = text
    ta.style.position = 'fixed'
    ta.style.opacity = '0'
    document.body.appendChild(ta)
    ta.select()
    const ok = document.execCommand('copy')
    document.body.removeChild(ta)
    return ok
  }
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob)
  const a   = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

function slug(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
}
